#!/usr/bin/env ruby

require "thor"
require "encruby"
require "encruby/cli"

begin
  Encruby::CLI.start ARGV
rescue Encruby::Error => e
  STDERR.puts "\x1b[31m[ERROR]: #{e.message}\x1b[0m"
  exit 1
# rescue StandardError => e
#   STDERR.puts "\x1b[31m[FATAL]: #{e.message}\x1b[0m"
#   exit 2
end
