#!/usr/bin/env ruby

require "thor"
require "encruby"
require "encruby/cli"

begin
  Encruby::CLI.start ARGV
rescue Encruby::Error => e
  Thor::Shell::Color.new.say_status("ERROR", e.message, :red)
  exit 1
rescue StandardError => e
  Thor::Shell::Color.new.say_status("FATAL", e.message, :red)
  Thor::Shell::Color.new.say_status("FATAL", e.backtrace.join("\n"), :yellow)
  exit 2
end
